### ISSUE TITLE
Openssl needed

### ISSUE THREAD

**Issue by frdbr** [flathub/org.kde.kdenlive#102]
Next version (21.04) will need openssl for a new feature to download resources online.

**Comment by tsdgeos** [comment]
openssl is already part of the sdk, isn't it?

**Comment by eszlari** [comment]
Apparently, this requires `--enable-nonfree`, which makes this a no-go. See also: https://github.com/flathub/org.kde.kdenlive/issues/86

**Comment by jlskuz** [comment]
No, we don't need openssl for the online resources (I don't know if we need it for something else…
gnutls works as well and is already enabled after my request at #86
