### ISSUE TITLE
missing canberra-gtk-module

### ISSUE THREAD

**Issue by feri777** [flathub/org.kde.kdenlive#13]
Hello. I have this error after I run kdenlive. There is warnings from terminal:

> ~$ flatpak run org.kde.kdenlive
> 
> (kdenlive:2): Gtk-WARNING **: Theme parsing error: gtk.css:5978:26: 'titlebar_fg_color' is not a valid color name
> Gtk-Message: Failed to load module "canberra-gtk-module"
> Gtk-Message: Failed to load module "canberra-gtk-module"
> Qt: Session management error: Could not open network socket
> trying to load "/usr/lib/plugins/kf5/kio/file.so" from "/usr/lib/plugins/kf5/kio/file.so"

**Comment by TingPing** [comment]
The Gtk one at least is a harmless warning you can ignore.
