### ISSUE TITLE
Disable movit by default

### ISSUE THREAD

**Issue by eiglow** [flathub/org.kde.kdenlive#134]
Movit is very unstable and generally unusable. When it's on, it even says this message in the bottom right corner:
![Screenshot_20210520_173244](https://user-images.githubusercontent.com/16441870/118941932-69b81400-b991-11eb-9f19-133c6cd6e2b1.png)
Why is it on by default? It should be disabled by default, as it is in the appimage.

**Comment by tsdgeos** [comment]
@eszlari ↑ ?

**Comment by eiglow** [comment]
Actually I think this is my fault. I must have turned movit on when using the kdenlive flatpak a while ago, uninstalled it, and then much later, reinstalled it, forgetting that my config files persisted.
