### ISSUE TITLE
Jobs stuck in "waiting"

### ISSUE THREAD

**Issue by ctron** [flathub/org.kde.kdenlive#135]
When rendering, jobs are stuck for me in "waiting", although in the background they render just fine. Problem is, that you don't really know how far they are and kdenlive complains about pending jobs when shutting down.

I know that used to work in the past, though I am not sure when it broke.

I found the following link on, it mentions "bad packaging": https://www.reddit.com/r/kdenlive/comments/gu0wz4/rendering_anything_gets_stuck_on_waiting/ … although this seems to be for app image, maybe the flathub packaging has a problem now as well.

**Comment by ctron** [comment]
Fixed for me, thanks!

**Comment by mmassenzio** [comment]
This just happened to me, with a very recent flatpak install of kdenlive:
```
Kdenlive: 23.08.2
Package Type: flatpak
MLT: 7.21.0
Qt: 5.15.10 (built against 5.15.10 x86_64-little_endian-lp64)
Frameworks: 5.111.0
System: KDE Flatpak runtime
Kernel: linux 6.5.0-10-generic
CPU: x86_64
Windowing System: xcb
Movit (GPU): disabled
Track Compositing: qtblend
```
> although in the background they render just fine
how do you check for that?

```
└─( lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic

└─( uname -a
Linux gondor 6.5.0-10-generic #10-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 13 13:49:38 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
Suggestions?
