### ISSUE TITLE
Open project with Flathub version does not maintain the aspect ratio.

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.kde.kdenlive#14]
I made this project with Kdenlive of the PPA
(ppa: kdenlive / kdenlive-stable) in Ubuntu.
I currently have the Flathub version installed.
When I open the project it does not save the aspect ratio.
I have to deactivate and activate to fix it.

Video of what happens:  https://yadi.sk/i/4UPcedYz3VugHo

**Comment by eszlari** [comment]
I think you should report this upstream: https://bugs.kde.org/

**Comment by eszlari** [comment]
Have you filed an upstream bug?

**Comment by alexb3d** [comment]
Here it is https://bugs.kde.org/show_bug.cgi?id=394287
