### ISSUE TITLE
Flatpak instructions incorrect

### ISSUE THREAD

**Issue by cefn** [flathub/org.kde.kdenlive#17]
At https://kdenlive.org/en/download/ under the flatpak heading the following instructions are provided

```
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak --user install flathub org.kde.kdenlive

Then start it with:
$ flatpak run org.kde.kdenlive
```

However, these instructions don't appear to work. Both `flatpak remote-add` and `flatpak install` need to be prefixed with --user or neither of them. Otherwise, the remote is added in the system mode, which is not visible to the user mode, meaning you get the following error...

> error: Unable to load summary from remote flathub: Remote "flathub" not found

**Comment by eszlari** [comment]
The website has been fixed.

**Comment by Sphinxs** [comment]
I have this error today :

`error: Unable to load summary from remote flathub: Remote "flathub" not found`

02 / 06 / 2018

**Comment by cefn** [comment]
Did you run 

```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

...in order to configure the repository with the name flathub? The error looks like the same error I got when I forgot to actually set up flatpak with any repositories.

I had success following the instructions at https://flatpak.org/setup/Ubuntu/ to set things up, which included the above line. 

Other operating systems are listed at https://flatpak.org/setup/
