### ISSUE TITLE
cant load the qt platform plugin wayland even though it was found

### ISSUE THREAD

**Issue by joergister** [flathub/org.kde.kdenlive#18]
if type 
`flatpak run -v org.kde.kdenlive`
 I get 

```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Disallowing network access
F: Allowing dri access
F: Allowing host-fs access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/user/.config/pulse/client.conf': Fehler beim Öffnen der Datei »/home/user/.config/pulse/client.conf«: No such file or directory


Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

So the platform plugin is somehow in place, but can not be initialized....
What's weird is `Could not load the Qt platform plugin "wayland" in ""`
Because: what is "" ? is it a directory that doesn't exist or what?

**Comment by eszlari** [comment]
What's the distribution? Flatpak version? I guess wayland is running on the host system?!

**Comment by joergister** [comment]
Fedora 28
Flatpak 0.11.7

Well, but qt is bundled into the KDE runtime afaik and so is the qt wayland Plugin

**Comment by eszlari** [comment]
I tested this on a Fedora 28 Live system and Kdenlive runs normally. When I try to start it with...
```
flatpak run --socket=wayland org.kde.kdenlive
```
I get...
```
QSocketNotifier: Can only be used with threads started with QThread
Using Wayland-EGL
Using the 'xdg-shell-v6' shell integration
trying to load "/usr/lib/plugins/kf5/kio/file.so" from "/usr/lib/plugins/kf5/kio/file.so"
Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
ASSERT failure in QCoreApplication::sendEvent: "Cannot send events to objects owned by a different thread. Current thread 0x0x2708aa0. Receiver 'QOffscreenSurface' (of type 'QWindow') was created in thread 0x0x4251b30", file kernel/qcoreapplication.cpp, line 576

```
So it seems Kdenlive does not work with wayland natively at the moment.

**Comment by joergister** [comment]
Well remember I tried to run `flatpak run -v org.kde.kdenlive` and got the error I reported. 
I was running a plasma session under wayland.
now, same setup, not new updates from the fedora repo or from the flathub, but running this command 

`flatpak run -v --socket=wayland org.kde.kdenlive`

I get the following output:


```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/joris/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/joris/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Disallowing network access
F: Allowing dri access
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/joris/.config/pulse/client.conf': Fehler beim Öffnen der Datei »/home/joris/.config/pulse/client.conf«: No such file or directory
Using Wayland-EGL
Using the 'xdg-shell-v6' shell integration
trying to load "/usr/lib/plugins/kf5/kio/file.so" from "/usr/lib/plugins/kf5/kio/file.so"
Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
```


And then, I had a running kdenlive session, was able to open a project, edit it and render it. Everything worked just fine.

but starting from the gui, doesn't work. 
so, it depends on the command.

and the `exec` command from kdenlives `.desktop` file doesn't seem to be a command, that works.
It actually is 
`Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=kdenlive --file-forwarding org.kde.kdenlive @@u %U @@`

**Comment by eszlari** [comment]
What GPU do you have?


> and the exec command from kdenlives .desktop file doesn't seem to be a command, that works.

That's how flatpak works, it substitutes the command in the .desktop file.

You could edit the command in the menu, but a KDE bug prevents that:
https://bugs.kde.org/show_bug.cgi?id=394476

**Comment by joergister** [comment]
I have a laptop with an intel GPU and a second nvidia GPU although I don't use the NVIDIA GPU,
No nvidia drivers installed, only mesa and nouveau


`00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09) (prog-if 00 [VGA controller])
        Subsystem: Lenovo Device 21d0
        Flags: bus master, fast devsel, latency 0, IRQ 26
        Memory at f1400000 (64-bit, non-prefetchable) [size=4M]
        Memory at e0000000 (64-bit, prefetchable) [size=256M]
        I/O ports at 6000 [size=64]
        [virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: i915
        Kernel modules: i915
`


`01:00.0 VGA compatible controller: NVIDIA Corporation GF119M [Quadro NVS 4200M] (rev a1) (prog-if 00 [VGA controller])
        Subsystem: Lenovo Device 21d0
        Flags: bus master, fast devsel, latency 0, IRQ 27
        Memory at f0000000 (32-bit, non-prefetchable) [size=16M]
        Memory at c0000000 (64-bit, prefetchable) [size=256M]
        Memory at d0000000 (64-bit, prefetchable) [size=32M]
        I/O ports at 5000 [size=128]
        Expansion ROM at f1000000 [disabled] [size=512K]
        Capabilities: <access denied>
        Kernel driver in use: nouveau
        Kernel modules: nouveau`


`glxinfo |grep Mesa`

gives me:

```
client glx vendor string: Mesa Project and SGI
    Device: Mesa DRI Intel(R) Sandybridge Mobile  (0x126)
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.0.2
OpenGL version string: 3.0 Mesa 18.0.2
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.0.2




```

**Comment by eszlari** [comment]
Since you are running Fedora 28:
A Plasma 5.13 update is now available and afaik they changed Qt's backend selection there. So does it work out of the box now?

**Comment by joergister** [comment]
I will test that tomorrow.

**Comment by joergister** [comment]
works now in a wayland session from the gui, using `flatpak run -v org.kde.kdenlive` and using `flatpak run --socket=wayland org.kde.kdenlive`
using the last command I get:

```
Using Wayland-EGL
Using the 'xdg-shell-v6' shell integration
trying to load "/usr/lib/plugins/kf5/kio/file.so" from "/usr/lib/plugins/kf5/kio/file.so"
Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
ASSERT failure in QCoreApplication::sendEvent: "Cannot send events to objects owned by a different thread. Current thread 0x0x2393aa0. Receiver '' (of type 'QOffscreenSurface') was created in thread 0x0x26990c0", file kernel/qcoreapplication.cpp, line 576
```

and a working kdenlive session using the wayland backend.

using 
`flatpak run -v org.kde.kdenlive`

I get 

```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 3426198457
F: Allocated instance id 3813885021
F: Disallowing network access
F: Allowing dri access
F: Allowing host-fs access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/user/.config/pulse/client.conf': Fehler beim Öffnen der Datei »/home/user/.config/pulse/client.conf«: No such file or directory
F: Running 'bwrap --args 23 /usr/libexec/flatpak-dbus-proxy --args=25'
F: Running 'bwrap --args 22 kdenlive'
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Qt: Session management error: Could not open network socket
trying to load "/usr/lib/plugins/kf5/kio/file.so" from "/usr/lib/plugins/kf5/kio/file.so"
qt.qpa.xcb: QXcbConnection: XCB error: 8 (BadMatch), sequence: 5376, resource id: 56623383, major code: 151 (Unknown), minor code: 11
qt.qpa.xcb: QXcbConnection: XCB error: 8 (BadMatch), sequence: 8951, resource id: 56623502, major code: 130 (Unknown), minor code: 3
qt.qpa.xcb: QXcbConnection: XCB error: 8 (BadMatch), sequence: 8983, resource id: 56623502, major code: 130 (Unknown), minor code: 3
qt.qpa.xcb: QXcbConnection: XCB error: 8 (BadMatch), sequence: 8986, resource id: 56623502, major code: 130 (Unknown), minor code: 3
```
but still a working kdenlive session although a session using the xcb window system. 
Starting from the GUI (also in a Wayland session) also results in a working xcb session.

You were probably right: they have changed something in the qt backend selection since now, all kde apps use the xcb backend although I'm running a wayland session.
