### ISSUE TITLE
Errors while running

### ISSUE THREAD

**Issue by ahangarha** [flathub/org.kde.kdenlive#19]
After installation, I get this error:

    error: app/org.kde.kdenlive/x86_64/master not installed

**Update:**
Though I didn't get any error while installing, I trying reinstall it again. And this is what I get after running the app using `flatpak run org.kde.kdenlive`:

```
Qt: Session management error: Could not open network socket
++++++++
.
.
.
org.kde.multimedia.kdenlive: ("update-mime-database", "/home/MYUSER/.var/app/org.kde.kdenlive/data/mime/") exited with error code -2
trying to load "/usr/lib/plugins/kf5/kio/file.so" from "/usr/lib/plugins/kf5/kio/file.so"
qt.qpa.xcb: QXcbConnection: XCB error: 8 (BadMatch), sequence: 8385, resource id: 75497894, major code: 155 (Unknown), minor code: 11

```
The app is working, but I am worried it crashes somewhere in the middle of editing.

**Comment by eszlari** [comment]
These errors are harmless.
