### ISSUE TITLE
Fails to start (NVidia driver)

### ISSUE THREAD

**Issue by CitrusAlex** [flathub/org.kde.kdenlive#20]
I have Arch Linux with Nvidia driver (396.24.10) installed and Kdenlive fails to launch with these errors:

> flatpak run org.kde.kdenlive
> Gtk-Message: Failed to load module "canberra-gtk-module"
> Gtk-Message: Failed to load module "canberra-gtk-module"
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> Could not initialize GLX
> 

I had the exact same issue on Ubuntu 18.04. Regular package from arch repos seems to work just fine, and AppImage too.

**Comment by TingPing** [comment]
This is the wrong place to report it, but 396.24.10 is some beta version of the driver and currently we don't package those. If you update to the current stable release 396.45 it will be packaged.

**Comment by CitrusAlex** [comment]
Yep, didn't know flatpak doesn't support beta drivers. Updating to 396.45 solved the problem.
