### ISSUE TITLE
Bezier Curves causes crash

### ISSUE THREAD

**Issue by Efenstor** [flathub/org.kde.kdenlive#225]
In the latest release (23.04.1) adding the Bezier Curves to a clip causes crash. No special conditions needed, just add any clip then drag and drop the effect. My OS is Debian 11 (amd64), video card is Radeon with free drivers.

**Comment by tsdgeos** [comment]
Please report this at bugs.kde.org

If the developers confirm is a specific flathub packaging problem come back and reopen this issue.

**Comment by Efenstor** [comment]
I tested the official AppImage and there is no crash. Does it imply it's the flatpack version issue?

**Comment by tsdgeos** [comment]
Please describe exactly what you do to make it crash as if we had no idea how kdenlive works

**Comment by Efenstor** [comment]
It crashes with the "double free or corruption (!prev)" message in the terminal, so it's not clear whether it's really caused by flatpak or something else which becomes apparent only in the flatpak environment. Let's wait what the devs say, I have opened a ticket at bugs.kde.org with the full details: https://bugs.kde.org/show_bug.cgi?id=469693

**Comment by Efenstor** [comment]
The new release of frei0r is out! https://github.com/dyne/frei0r/releases/tag/v2.3.0

**Comment by travier** [comment]
It's bumped in https://github.com/flathub/org.kde.kdenlive/pull/226.
