### ISSUE TITLE
i can not exit to full screen

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.kde.kdenlive#3]
Hello, I recently installed kdenlive flatpak and the default screen in full screen, I try to return to normal size with Ctrl + shift + f, and nothing happens, also from the menu and nothing happens, the window is still full screen. In addition, the application starts too slow. linuxmint 18.3 64 bit

**Comment by TingPing** [comment]
Just a guess, <kbd>f11</kbd>

**Comment by eszlari** [comment]
I just tested CTRL+SHIFT+F in KDE and GNOME and it works in both, so this must be mint specific problem.

For the slow startup see: https://github.com/flatpak/flatpak/issues/589
