### ISSUE TITLE
The Kdenlive flatpak still using org.kde.Platform version 5.12

### ISSUE THREAD

**Issue by codewiz** [flathub/org.kde.kdenlive#30]
https://github.com/flathub/org.kde.kdenlive/blob/f666be83ee3c591d535d1162a15f6ff314ea0f99/org.kde.kdenlive.yaml#L4

Is this intentional? KDE 5.12 was missing many UI improvements, particularly in Wayland support and HiDPI support

**Comment by eszlari** [comment]
The version number correlates with Qt, not KDE.

**Comment by nedrichards** [comment]
Yes, the KDE runtime always uses the latest version of the KDE libraries, but has a stable version of Qt and a stable underlying Freedesktop SDK (e.g. 5.9 uses FDo 1.6 and Qt 5.9, 5.12 uses FDo 18.08 and Qt 5.12)
