### ISSUE TITLE
After updating the video card drivers, the program stopped running.

### ISSUE THREAD

**Issue by CyberHippy1991** [flathub/org.kde.kdenlive#305]
[console-log.txt](https://github.com/flathub/org.kde.kdenlive/files/13540408/console-log.txt)
Presumably, after updating the drivers for the radeon rx 6600, kde live installed from flatpak stopped running. Updated from version 23.2.1 to 23.3.0.
When trying to launch, the message appears "During the last launch of Kdenlive, a failure occurred. Reset the configuration files to their original values?", if click reset or continue, the program does not start.
If run it through the terminal and select reset, you get the following message in the terminal:

witcher@witcher-MS-7B86:~$ flatpak run org.kde.kdenlive
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Warning: fallback to QtQuick software backend.
Qt: Session management error: Could not open network socket
 = = = =
GOT Deleted file:  "/home/witcher/.var/app/org.kde.kdenlive/config/kdenlive-flatpakrc"
QPaintDevice: Cannot destroy paint device that is being painted

If choose to continue:

witcher@witcher-MS-7B86:~$ flatpak run org.kde.kdenlive
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Warning: fallback to QtQuick software backend.
Qt: Session management error: Could not open network socket
profilePath from appDir/../share:  "/app/share/mlt-7/profiles"
meltPath from KdenliveSetting::meltPath:  "/app/bin/melt"
Empty metadata for  "telecide"
Empty metadata for  "glsl.manager"
plugin not available: "avfilter.acompressor"
plugin not available: "avfilter.aecho"
plugin not available: "avfilter.agate"
plugin not available: "avfilter.atadenoise"
plugin not available: "avfilter.bs2b"
plugin not available: "avfilter.bwdif"
plugin not available: "avfilter.deblock"
plugin not available: "avfilter.dedot"
plugin not available: "avfilter.deflate"
plugin not available: "avfilter.derain"
plugin not available: "avfilter.doubleweave"
plugin not available: "avfilter.field"
plugin not available: "avfilter.framestep"
plugin not available: "avfilter.fspp"
plugin not available: "avfilter.graphmonitor"
plugin not available: "avfilter.hqdn3d"
plugin not available: "avfilter.inflate"
plugin not available: "avfilter.lagfun"
plugin not available: "avfilter.loudnorm"
plugin not available: "avfilter.random"
plugin not available: "avfilter.removegrain"
plugin not available: "avfilter.separatefields"
plugin not available: "avfilter.shuffleplanes"
plugin not available: "avfilter.sofalizer"
plugin not available: "avfilter.sr"
plugin not available: "avfilter.tmix"
plugin not available: "avfilter.w3fdif"
plugin not available: "avfilter.weave"
plugin not available: "avfilter.yadif"
plugin not available: "frei0r.alpha0ps"
plugin not available: "frei0r.alpha0ps"
plugin not available: "frei0r.alphagrad"
plugin not available: "frei0r.alphaspot"
plugin not available: "frei0r.baltan"
plugin not available: "frei0r.bgsubtract0r"
plugin not available: "frei0r.delay0r"
plugin not available: "frei0r.delaygrab"
plugin not available: "frei0r.facebl0r"
plugin not available: "frei0r.facedetect"
plugin not available: "frei0r.hqdn3d"
plugin not available: "frei0r.lightgraffiti"
plugin not available: "frei0r.lightgraffiti"
plugin not available: "frei0r.pr0be"
plugin not available: "frei0r.pr0file"
plugin not available: "frei0r.tehRoxx0r"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "movit.unsharp_mask"
plugin not available: "timewarp"
unsupported effect in group "frei0r.alpha0ps" : "/app/share/kdenlive/effect-templates/secondary_color_correction.xml"
Asset "mask_start-frei0r.alphaspot" has invalid dependency "frei0r.alphaspot" and is going to be removed
plugin not available: "region"
=== /// CANNOT ACCESS SPEECH DICTIONARIES FOLDER
QQmlEngine::setContextForObject(): Object already has a QQmlContext
QQmlEngine::setContextForObject(): Object already has a QQmlContext
QQmlEngine::setContextForObject(): Object already has a QQmlContext
QQmlEngine::setContextForObject(): Object already has a QQmlContext
==========
FOUND SUPPORTED CODECS:  ("h264_vaapi", "hevc_vaapi")
// FFMPEG ARGS:  ("-hide_banner", "-filters")
/// ++ SCALE_NPP NOT SUPPORTED

System data:
OS: Linux Mint 20.3 x86_64 
Kernel: 6.1.65-x64v1-xanmod1 
Packages: 2632 (dpkg), 52 (flatpak) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: Cinnamon 
WM: Mutter (Muffin) 
WM Theme: Mint-X (Mint-Y) 
Theme: Mint-Y [GTK2/3] 
Icons: Mint-Y [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 3600 (12) @ 3.600GH 
GPU: AMD ATI 28:00.0 Device 73ff 
Memory: 6187MiB / 32039MiB

Screenshots of the problem.
![launch1](https://github.com/flathub/org.kde.kdenlive/assets/11318082/e3ecf56d-d2be-46a3-b450-73725a634001)
![launch2](https://github.com/flathub/org.kde.kdenlive/assets/11318082/d84b276a-3e03-4b82-9807-ddbb1de4e27e)
![launch3-1](https://github.com/flathub/org.kde.kdenlive/assets/11318082/5b8caded-953f-4c52-ad09-d73d8d68a296)
![launch3-2](https://github.com/flathub/org.kde.kdenlive/assets/11318082/baa89265-feb9-4fcb-a8cc-6cb7b1e4fc27)

**Comment by AdivonSlav** [comment]
I can confirm that I have the same issue and the same graphics card. On PopOS I updated to Mesa 23.3.0 and I'm unable to launch Kdenlive, including some other Flatpak apps that all report similar errors.

**Comment by travier** [comment]
Can you try the version from https://github.com/flathub/org.kde.kdenlive/pull/292 ? Thanks

**Comment by CyberHippy1991** [comment]
After installation with the command `flatpak install --user https://dl.flathub.org/build-repo/69830/org.kde.kdenlive.flatpakref`
The program started, a small project for 6 minutes was built. 

Screenshots and log are attached.
<details>
<summary>Screenshots</summary>

![1](https://github.com/flathub/org.kde.kdenlive/assets/11318082/70f45c4f-84a3-49f6-9d83-9eda04dc4d2a)

![2](https://github.com/flathub/org.kde.kdenlive/assets/11318082/7dbc6aa5-6972-4298-924c-b01b0a9ea342)

![3](https://github.com/flathub/org.kde.kdenlive/assets/11318082/1d4f5f7b-b782-4179-88ff-8e8ba7400163)

![4](https://github.com/flathub/org.kde.kdenlive/assets/11318082/1f7d6a5e-eebc-47c4-a9fb-098fea24358d)

![5](https://github.com/flathub/org.kde.kdenlive/assets/11318082/bcd53ced-a6f6-42c5-b32e-91846d4244bc)

![6](https://github.com/flathub/org.kde.kdenlive/assets/11318082/5879dd6f-5032-4c41-a5ab-f8a3caa59a50)

![7](https://github.com/flathub/org.kde.kdenlive/assets/11318082/9ff55da5-8832-42ad-902f-9bfaa5f9f302)

</details>

[console-log.txt](https://github.com/flathub/org.kde.kdenlive/files/13640039/console-log.txt)

**Comment by travier** [comment]
So it worked?

**Comment by AdivonSlav** [comment]
The version from #292 does indeed run. Is this some kind of regression that happened, or?

**Comment by travier** [comment]
You should uninstall the Flatpak from the test remote and then re-install the one from the stable Flathub remote. Your data will be kept as is.
