### ISSUE TITLE
kdenlive flatpak doesn't recognize theme + bug menu

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/org.kde.kdenlive#32]
self image explains

![kdenlive bug](https://user-images.githubusercontent.com/17401812/63052148-04c6b480-beb5-11e9-8e08-3f3ce10932e7.png)

fedora silverblue 30 GNOME

[fastos@localhost ~]$ flatpak info org.kde.kdenlive

Kdenlive - Editor de Vídeo

        ID: org.kde.kdenlive
       Ref: app/org.kde.kdenlive/x86_64/stable
      Arq.: x86_64
      Ramo: stable
    Versão: 19.04.3
   Licença: GPL-2.0+
    Origem: flathub
   Coleção: org.flathub.Stable
Instalação: system
 Instalado: 405,4 MB
   Runtime: org.kde.Platform/x86_64/5.12
       Sdk: org.kde.Sdk/x86_64/5.12

    Commit: ade668abe1f4f050cc4294752c11897372b2857af0b1c38bc636ae87fd692cf2
       Pai: 1f761e379c2e9c06b16dff80f5ba5c7d607ac02f01385bff8b5764f647889cac
   Assunto: v19.04.3 (a5cab82e)
      Data: 2019-07-12 06:08:59 +0000

**Comment by eszlari** [comment]
Does the AppImage behave differently?

**Comment by FastOSlinux** [comment]
> Does the AppImage behave differently?
kdenlive-19.04.3-x86_64.appimage

![2019-08-15_19-01](https://user-images.githubusercontent.com/17401812/63129900-2a27f100-bf8f-11e9-9073-71880f9c0044.png)

**Comment by eszlari** [comment]
Looks the same.

Have you installed `org.kde.KStyle.Adwaita`?
And what do you mean by "bug menu"?

**Comment by FastOSlinux** [comment]
> Looks the same.
> 
> Have you installed `org.kde.KStyle.Adwaita`?
> And what do you mean by "bug menu"?

org.kde.KStyle.Adwaita                                                          5.12 

![2019-08-15_22-11](https://user-images.githubusercontent.com/17401812/63136721-b5ae7b80-bfa9-11e9-9229-2fa6ee8164fd.png)

**Comment by eszlari** [comment]
The menu placement? Probably a wayland bug.

Btw: You can create screenshots with English UI by running:
```
$ LANG=en_US flatpak run org.kde.kdenlive
```
