### ISSUE TITLE
EoL-Warning for KDE 5.15-21.08

### ISSUE THREAD

**Issue by DarkSpir** [flathub/org.kde.kdenlive#323]
Flatpak warns about kdenlive needing/using dependencies that are EoL:
```
$ flatpak update
Looking for updates…

Info: runtime org.kde.Sdk branch 5.15-21.08 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK

Info: runtime org.kde.Platform branch 5.15-21.08 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   org.kde.kdenlive

Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   org.kde.kdenlive
```

**Comment by travier** [comment]
Did you mask updates for kdenlive? We've already moved it to the 23.08 platform.

**Comment by DarkSpir** [comment]
Thanks for pointing out. Turns out my Steam Deck comes with two remote repositories preconfigured (or I have added one years ago), flathub and kdeapps. For some reason it pulled kdenlive from the kdeapps repository and that's where the old flatpak comes from. I switched the source and now I can see the newer version. Thank you for putting me in the right direction.
