### ISSUE TITLE
crash on wayland

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/org.kde.kdenlive#34]
Fedora Silverblue 30
 Version: 30.20190814.0

just tried to open

$ flatpak run org.kde.kdenlive 
QSocketNotifier: Can only be used with threads started with QThread
Using Wayland-EGL
"qtext" is blacklisted
"resample" is blacklisted
"frei0r.3dflippo" is blacklisted
"frei0r.bluescreen0r" is blacklisted
"frei0r.bw0r" is blacklisted
"frei0r.gamma" is blacklisted
"frei0r.invert0r" is blacklisted
"frei0r.rgbsplit0r" is blacklisted
"frei0r.tehRoxx0r" is blacklisted
"frei0r.transparency" is blacklisted
"frei0r.vertigo" is blacklisted
"videostab" is blacklisted
"videostab2" is blacklisted
WARNING : Fails to parse  "telecide"
WARNING : Fails to parse  "deinterlace"
"rgblut" is blacklisted
"spot_remover" is blacklisted
"text" is blacklisted
"timer" is blacklisted
WARNING : Fails to parse  "audiochannels"
WARNING : Fails to parse  "audioconvert"
WARNING : Fails to parse  "data_feed"
"data_show" is blacklisted
WARNING : Fails to parse  "imageconvert"
"mask_apply" is blacklisted
"mask_start" is blacklisted
"mono" is blacklisted
"region" is blacklisted
"resize" is blacklisted
"transition" is blacklisted
"watermark" is blacklisted
"gtkrescale" is blacklisted
WARNING : Fails to parse  "avcolour_space"
WARNING : Fails to parse  "avcolor_space"
WARNING : Fails to parse  "avdeinterlace"
WARNING : Fails to parse  "swscale"
"avfilter.abench" is blacklisted
"avfilter.acompressor" is blacklisted
"avfilter.adelay" is blacklisted
"avfilter.aecho" is blacklisted
"avfilter.aemphasis" is blacklisted
"avfilter.aeval" is blacklisted
"avfilter.afade" is blacklisted
"avfilter.afftfilt" is blacklisted
"avfilter.agate" is blacklisted
"avfilter.ametadata" is blacklisted
"avfilter.arealtime" is blacklisted
"avfilter.ashowinfo" is blacklisted
"avfilter.channelmap" is blacklisted
"avfilter.chorus" is blacklisted
"avfilter.earwax" is blacklisted
"avfilter.volume" is blacklisted
"avfilter.volumedetect" is blacklisted
"avfilter.atadenoise" is blacklisted
"avfilter.avgblur" is blacklisted
"avfilter.bbox" is blacklisted
"avfilter.bench" is blacklisted
"avfilter.blackdetect" is blacklisted
"avfilter.blackframe" is blacklisted
"avfilter.boxblur" is blacklisted
"avfilter.bwdif" is blacklisted
"avfilter.chromakey" is blacklisted
"avfilter.colorkey" is blacklisted
"avfilter.colormatrix" is blacklisted
"avfilter.colorspace" is blacklisted
"avfilter.convolution" is blacklisted
"avfilter.crop" is blacklisted
"avfilter.cropdetect" is blacklisted
"avfilter.curves" is blacklisted
"avfilter.datascope" is blacklisted
"avfilter.dctdnoiz" is blacklisted
"avfilter.deband" is blacklisted
"avfilter.deflate" is blacklisted
"avfilter.deinterlace_vaapi" is blacklisted
"avfilter.deshake" is blacklisted
"avfilter.despill" is blacklisted
"avfilter.doubleweave" is blacklisted
"avfilter.drawbox" is blacklisted
"avfilter.drawgraph" is blacklisted
"avfilter.drawgrid" is blacklisted
"avfilter.drawtext" is blacklisted
"avfilter.elbg" is blacklisted
"avfilter.eq" is blacklisted
"avfilter.fade" is blacklisted
"avfilter.field" is blacklisted
"avfilter.fieldhint" is blacklisted
"avfilter.fieldorder" is blacklisted
"avfilter.find_rect" is blacklisted
"avfilter.floodfill" is blacklisted
"avfilter.fspp" is blacklisted
"avfilter.gblur" is blacklisted
"avfilter.geq" is blacklisted
"avfilter.hflip" is blacklisted
"avfilter.hqdn3d" is blacklisted
"avfilter.hqx" is blacklisted
"avfilter.hue" is blacklisted
"avfilter.hwdownload" is blacklisted
"avfilter.idet" is blacklisted
"avfilter.il" is blacklisted
"avfilter.lenscorrection" is blacklisted
"avfilter.loop" is blacklisted
"avfilter.lumakey" is blacklisted
"avfilter.lut" is blacklisted
"avfilter.lutrgb" is blacklisted
"avfilter.lutyuv" is blacklisted
"avfilter.mcdeint" is blacklisted
"avfilter.metadata" is blacklisted
"avfilter.negate" is blacklisted
"avfilter.nlmeans" is blacklisted
"avfilter.nnedi" is blacklisted
"avfilter.owdenoise" is blacklisted
"avfilter.pad" is blacklisted
"avfilter.perspective" is blacklisted
"avfilter.phase" is blacklisted
"avfilter.pixscope" is blacklisted
"avfilter.pp" is blacklisted
"avfilter.pp7" is blacklisted
"avfilter.prewitt" is blacklisted
"avfilter.realtime" is blacklisted
"avfilter.removegrain" is blacklisted
"avfilter.removelogo" is blacklisted
"avfilter.roberts" is blacklisted
"avfilter.rotate" is blacklisted
"avfilter.scale_vaapi" is blacklisted
"avfilter.showinfo" is blacklisted
"avfilter.shuffleframes" is blacklisted
"avfilter.sidedata" is blacklisted
"avfilter.signalstats" is blacklisted
"avfilter.sobel" is blacklisted
"avfilter.stereo3d" is blacklisted
"avfilter.super2xsai" is blacklisted
"avfilter.swapuv" is blacklisted
"avfilter.tblend" is blacklisted
"avfilter.tlut2" is blacklisted
"avfilter.tonemap" is blacklisted
"avfilter.transpose" is blacklisted
"avfilter.vectorscope" is blacklisted
"avfilter.vflip" is blacklisted
"avfilter.vignette" is blacklisted
"avfilter.vmafmotion" is blacklisted
"avfilter.w3fdif" is blacklisted
"avfilter.xbr" is blacklisted
"avfilter.yadif" is blacklisted
"avfilter.zoompan" is blacklisted
WARNING : Fails to parse  "swresample"
WARNING : Fails to parse  "glsl.manager"
WARNING : Fails to parse  "movit.convert"
WARNING : Fails to parse  "movit.crop"
WARNING : Fails to parse  "movit.resample"
WARNING : Fails to parse  "movit.resize"
"motion_est" is blacklisted
WARNING : Fails to parse  "crop_detect"
WARNING : Fails to parse  "jack"
"jackrack" is blacklisted
++++++ Unknown asset :  "avfilter.acompressor"
++++++ Unknown asset :  "avfilter.aecho"
++++++ Unknown asset :  "avfilter.agate"
Warning: duplicate custom definition of effect "frei0r.alpha0ps" found. Only last one will be considered. Duplicate found in "/app/share/kdenlive/effects/frei0r_alpha0ps.xml"
Warning: duplicate custom definition of effect "frei0r.balanc0r" found. Only last one will be considered. Duplicate found in "/app/share/kdenlive/effects/frei0r_balanc0r.xml"
Warning: duplicate custom definition of effect "frei0r.curves" found. Only last one will be considered. Duplicate found in "/app/share/kdenlive/effects/frei0r_curves.xml"
Warning: duplicate custom definition of effect "frei0r.levels" found. Only last one will be considered. Duplicate found in "/app/share/kdenlive/effects/frei0r_levels.xml"
Warning: duplicate custom definition of effect "frei0r.lightgraffiti" found. Only last one will be considered. Duplicate found in "/app/share/kdenlive/effects/frei0r_lightgraffiti.xml"
Warning: duplicate custom definition of effect "frei0r.select0r" found. Only last one will be considered. Duplicate found in "/app/share/kdenlive/effects/frei0r_select0r.xml"
Warning: duplicate custom definition of effect "frei0r.sopsat" found. Only last one will be considered. Duplicate found in "/app/share/kdenlive/effects/frei0r_sopsat.xml"
++++++ Unknown asset :  "frei0r.tehRoxx0r"
++++++ Unknown asset :  "frei0r.vertigo"
++++++ Unknown asset :  "frei0r.vertigo"
++++++ Unknown asset :  "movit.unsharp_mask"
Warning: duplicate custom definition of effect "qtblend" found. Only last one will be considered. Duplicate found in "/app/share/kdenlive/effects/qtblend.xml"
++++++ Unknown asset :  "region"
++++++ Unknown asset :  "timewarp"
++++++ Unknown asset :  "opencv.tracker"
"frei0r.alphainjection" is blacklisted
"frei0r.blend" is blacklisted
"frei0r.composition" is blacklisted
"frei0r.xfade0r" is blacklisted
"0 instead of 1 arguments to message {%1 ips} supplied before conversion."
"0 instead of 1 arguments to message {%1 ips} supplied before conversion."
Using the 'xdg-shell' shell integration
Loading bin playlist...
//////////////////////
Trying to construct 5 tracks.
////////////////////////////////
SUSPICIOUS: we weren't expecting a producer when parsing the timeline
i18n() needs at least one parameter
i18n() needs at least one parameter
i18n() needs at least one parameter

$ flatpak info org.kde.kdenlive

Kdenlive - Editor de Vídeo

        ID: org.kde.kdenlive
       Ref: app/org.kde.kdenlive/x86_64/stable
      Arq.: x86_64
      Ramo: stable
    Versão: 19.08.0
   Licença: GPL-2.0+
    Origem: flathub
   Coleção: org.flathub.Stable
Instalação: system
 Instalado: 407,5 MB
   Runtime: org.kde.Platform/x86_64/5.12
       Sdk: org.kde.Sdk/x86_64/5.12

    Commit: 4be00ba9f72be303b349246f42d20fb7955825da3e6a55ef2e03397a3d4cba23
       Pai: 34cb832621e2b5f93f08506ea825df94bede31019d201f016eca7b35e978aa5c
   Assunto: fix appdata (862dcce9)
      Data: 2019-08-16 03:28:38 +0000

$ flatpak --version 
Flatpak 1.4.2

**Comment by eszlari** [comment]
What's the output of
```
$ journalctl
```
?

Anyway, you should probably report this upstream:
https://invent.kde.org/kde/kdenlive/issues

**Comment by FastOSlinux** [comment]
> What's the output of
> 
> ```
> $ journalctl
> ```
> 
> ?
> 
> Anyway, you should probably report this upstream:
> https://invent.kde.org/kde/kdenlive/issues

works with appimage


$ journalctl -n
-- Logs begin at Sat 2019-07-27 05:26:25 -03, end at Tue 2019-08-20 17:51:15 -03. --
ago 20 17:50:35 localhost.localdomain org.kde.kdenlive.desktop[1740]: ////////////////////////////////
ago 20 17:50:35 localhost.localdomain org.kde.kdenlive.desktop[1740]: SUSPICIOUS: we weren't expecting a producer when parsing the timeline
ago 20 17:50:35 localhost.localdomain org.kde.kdenlive.desktop[1740]: i18n() needs at least one parameter
ago 20 17:50:35 localhost.localdomain org.kde.kdenlive.desktop[1740]: i18n() needs at least one parameter
ago 20 17:50:57 localhost.localdomain gnome-shell[1740]: JS ERROR: TypeError: this._workspacesViews[i] is undefined
                                                         _updateWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:714:13
                                                         setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:704:9
                                                         setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/viewSelector.js:293:9
                                                         _updateWorkspacesGeometry@resource:///org/gnome/shell/ui/overviewControls.js:456:9
                                                         vfunc_allocate@resource:///org/gnome/shell/ui/overviewControls.js:389:9
                                                         _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:637:13
                                                         show@resource:///org/gnome/shell/ui/workspacesView.js:557:9
                                                         show@resource:///org/gnome/shell/ui/viewSelector.js:268:9
                                                         _animateVisible@resource:///org/gnome/shell/ui/overview.js:527:9
                                                         show@resource:///org/gnome/shell/ui/overview.js:513:9
                                                         toggle@resource:///org/gnome/shell/ui/overview.js:636:13
                                                         _initializeUI/<@resource:///org/gnome/shell/ui/main.js:190:13
ago 20 17:51:01 localhost.localdomain gnome-shell[1740]: JS ERROR: TypeError: this._workspacesViews[i] is undefined
                                                         _updateWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:714:13
                                                         setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:704:9
                                                         setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/viewSelector.js:293:9
                                                         _updateWorkspacesGeometry@resource:///org/gnome/shell/ui/overviewControls.js:456:9
                                                         vfunc_allocate@resource:///org/gnome/shell/ui/overviewControls.js:389:9
                                                         _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:637:13
                                                         show@resource:///org/gnome/shell/ui/workspacesView.js:557:9
                                                         show@resource:///org/gnome/shell/ui/viewSelector.js:268:9
                                                         _animateVisible@resource:///org/gnome/shell/ui/overview.js:527:9
                                                         show@resource:///org/gnome/shell/ui/overview.js:513:9
                                                         toggle@resource:///org/gnome/shell/ui/overview.js:636:13
                                                         _initializeUI/<@resource:///org/gnome/shell/ui/main.js:190:13
ago 20 17:51:03 localhost.localdomain systemd[1096]: dbus-:1.2-org.gnome.Characters.BackgroundService@7.service: Succeeded.
ago 20 17:51:04 localhost.localdomain gnome-shell[1740]: JS ERROR: TypeError: this._workspacesViews[i] is undefined
                                                         _updateWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:714:13
                                                         setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:704:9
                                                         setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/viewSelector.js:293:9
                                                         _updateWorkspacesGeometry@resource:///org/gnome/shell/ui/overviewControls.js:456:9
                                                         vfunc_allocate@resource:///org/gnome/shell/ui/overviewControls.js:389:9
                                                         _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:637:13
                                                         show@resource:///org/gnome/shell/ui/workspacesView.js:557:9
                                                         show@resource:///org/gnome/shell/ui/viewSelector.js:268:9
                                                         _animateVisible@resource:///org/gnome/shell/ui/overview.js:527:9
                                                         show@resource:///org/gnome/shell/ui/overview.js:513:9
                                                         toggle@resource:///org/gnome/shell/ui/overview.js:636:13
                                                         _initializeUI/<@resource:///org/gnome/shell/ui/main.js:190:13
ago 20 17:51:12 localhost.localdomain gnome-shell[1740]: JS ERROR: TypeError: this._workspacesViews[i] is undefined
                                                         _updateWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:714:13
                                                         setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:704:9
                                                         setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/viewSelector.js:293:9
                                                         _updateWorkspacesGeometry@resource:///org/gnome/shell/ui/overviewControls.js:456:9
                                                         vfunc_allocate@resource:///org/gnome/shell/ui/overviewControls.js:389:9
                                                         _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:637:13
                                                         show@resource:///org/gnome/shell/ui/workspacesView.js:557:9
                                                         show@resource:///org/gnome/shell/ui/viewSelector.js:268:9
                                                         _animateVisible@resource:///org/gnome/shell/ui/overview.js:527:9
                                                         show@resource:///org/gnome/shell/ui/overview.js:513:9
                                                         toggle@resource:///org/gnome/shell/ui/overview.js:636:13
                                                         _initializeUI/<@resource:///org/gnome/shell/ui/main.js:190:13
ago 20 17:51:15 localhost.localdomain gnome-shell[1740]: JS ERROR: TypeError: this._workspacesViews[i] is undefined
                                                         _updateWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:714:13
                                                         setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:704:9
                                                         setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/viewSelector.js:293:9
                                                         _updateWorkspacesGeometry@resource:///org/gnome/shell/ui/overviewControls.js:456:9
                                                         vfunc_allocate@resource:///org/gnome/shell/ui/overviewControls.js:389:9
                                                         _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:637:13
                                                         show@resource:///org/gnome/shell/ui/workspacesView.js:557:9
                                                         show@resource:///org/gnome/shell/ui/viewSelector.js:268:9
                                                         _animateVisible@resource:///org/gnome/shell/ui/overview.js:527:9
                                                         show@resource:///org/gnome/shell/ui/overview.js:513:9
                                                         toggle@resource:///org/gnome/shell/ui/overview.js:636:13
                                                         _initializeUI/<@resource:///org/gnome/shell/ui/main.js:190:13

**Comment by johns2s** [comment]
@FastOSlinux did you find a solution?

**Comment by FastOSlinux** [comment]
> @FastOSlinux did you find a solution?

no, it's upstream bug right?

**Comment by johns2s** [comment]
> > @FastOSlinux did you find a solution?
> 
> no, it's upstream bug right?

I don't think it is - I'm also only getting this on Flatpak. Could be fixed in F31 with [native QT Wayland](https://fedoraproject.org/wiki/Changes/Qt_Wayland_By_Default_On_Gnome) though.
