### ISSUE TITLE
Please package kednlive flatpack with ffmpeg built for NVENC  [Feature Request]

### ISSUE THREAD

**Issue by amoore2600** [flathub/org.kde.kdenlive#35]
I would really like to see the Kdenlive flatpack published with ffmpeg built with NVENC support include. 

Open Broadcast Studio OBS has start publishing their flatpack with ffmpeg with NVENC support. 

The flatpack system is ideal to include this with Kdenlive.

**Comment by eszlari** [comment]
fixed: https://github.com/flathub/org.kde.kdenlive/commit/5f0029578ba5152151af849a397687fa15a469e4
