### ISSUE TITLE
kdenlive wants to install org.freedesktop.Platform.openh264 but fails to install

### ISSUE THREAD

**Issue by jrg34567** [flathub/org.kde.kdenlive#38]
flatpak install  flathub org.kde.kdenlive results in:
Looking for matches…
Required runtime for org.kde.kdenlive/x86_64/stable (runtime/org.kde.Platform/x86_64/5.13) found in remote flathub
Do you want to install it? [Y/n]: y

org.kde.kdenlive permissions:
    ipc           network               pulseaudio            x11
    devices       file access [1]       dbus access [2]

    [1] host, xdg-config/kdeglobals:ro
    [2] com.canonical.AppMenu.Registrar

        ID                                  Arch   Branch Remote  Download
 1. [✓] org.kde.Platform                    x86_64 5.13   flathub 246.3 MB / 321.8 MB
 2. [✓] org.freedesktop.Platform.GL.default x86_64 19.08  flathub  90.8 MB / 90.8 MB
 3. [✗] org.freedesktop.Platform.openh264   x86_64 19.08  flathub 594.2 kB / 593.4 kB
 4. [✓] org.kde.KStyle.Adwaita              x86_64 5.13   flathub   5.8 MB / 5.8 MB
 5. [✓] org.kde.Platform.Locale             x86_64 5.13   flathub  16.7 kB / 337.7 MB
 6. [✓] org.kde.kdenlive                    x86_64 stable flathub  34.4 MB / 34.3 MB
 7. [✓] org.kde.kdenlive.Locale             x86_64 stable flathub   4.1 kB / 2.3 MB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.

**Comment by eszlari** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/886
