### ISSUE TITLE
Rendering with NVENC crashes

### ISSUE THREAD

**Issue by chocolateimage** [flathub/org.kde.kdenlive#417]
When rendering with "Hardware Accelerated (experimental)" I get this error that I don't get on native kdenlive:
```
Rendering of /mnt/somedata/Videos/exported/cvnfndndnd.mp4 crashed

Qt: Session management error: Could not open network socket
[hevc_nvenc @ 0x7480dc201b00] Driver does not support the required nvenc API version. Required: 12.2 Found: 12.1 [hevc_nvenc @ 0x7480dc201b00] The minimum required Nvidia driver for nvenc is (unknown) or newer
```

The command (the box when rendering in more options) is `ab=160k acodec=aac channels=2 f=mp4 real_time=-12 threads=12 vb=6000k vcodec=hevc_nvenc`

nvidia-smi says that that the CUDA version is on 12.2 but the flatpak version of kdenlive doesn't recognize it.

`org.freedesktop.Platform.GL.nvidia-535-183-01` is installed (same version as driver)

**Comment by travier** [comment]
Do you have an older GPU? Can you try the beta branch? https://github.com/flathub/org.kde.kdenlive#support-for-older-nvidia-gpus

**Comment by chocolateimage** [comment]
> Do you have an older GPU? Can you try the beta branch? https://github.com/flathub/org.kde.kdenlive#support-for-older-nvidia-gpus

I have a NVIDIA GeForce RTX 3060 so I don't know if that counts as old

**Comment by travier** [comment]
That's not old :)

**Comment by chocolateimage** [comment]
> That's not old :)

I am thinking something is happening with the flatpak version because in the system version it works (and the system has CUDA 12.2) but the flatpak seems to have CUDA 12.1 even though the same nvidia driver is installed in the flatpak (org.freedesktop.Platform.GL.nvidia-535-183-01)

**Comment by chocolateimage** [comment]
Still happens 2 weeks later (Linux Mint 21.3):
```
Rendering of /mnt/somedata/Videos/exported/testrender.mp4 crashed

Qt: Session management error: Could not open network socket
[hevc_nvenc @ 0x798538201b00] Driver does not support the required nvenc API version. Required: 12.2 Found: 12.1 [hevc_nvenc @ 0x798538201b00] The minimum required Nvidia driver for nvenc is (unknown) or newer
```

**Comment by travier** [comment]
Did you try the beta branch as I had asked?

**Comment by travier** [comment]
Made https://github.com/flathub/org.kde.kdenlive/pull/422 to try to update the beta branch.

**Comment by chocolateimage** [comment]
Seems like the issue was not an outdated GPU but rather an outdated driver (nvidia-driver-535), installing 550 seems to fix the issue: `sudo apt install nvidia-driver-550`
