### ISSUE TITLE
Why use pulseaudio instead of pipewire

### ISSUE THREAD

**Issue by Snowiiii** [flathub/org.kde.kdenlive#461]
Hello, I saw kdenlive uses Pulseaudio over Pipewire (https://github.com/flathub/org.kde.kdenlive/blob/master/org.kde.kdenlive.json#L18). Is this the reason of code limitations ?, Because there are many reasons to use Pipewire over Pulseaudio

**Comment by travier** [comment]
Pipewire provides backward compatibility with pulseaudio and uses the same socket.
