### ISSUE TITLE
Several entries are missing in the window to add clip or folder

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.kde.kdenlive#48]
I'm using Kdenlive on Arch linux, KDE Plasma 5.18.4.

open Kdenlive installed from flathub
right-click on "Project bin" area, choose "Add clip or folder"
Result: several entries of the side bar are missing.
If I press ctrl+o after opening Kdenlive, an file open dialog with all entries opens.

All entries are present when I follow the same steps with Kdenlive installed from Arch repos.
Compare the screenshots below.

Kdenlive from flathub:
![flatpak3](https://user-images.githubusercontent.com/15967631/78803350-469cf180-7995-11ea-8a53-3e0454edfeba.png)

Kdenlive from Arch repos:
![flatpak4](https://user-images.githubusercontent.com/15967631/78803501-75b36300-7995-11ea-8b39-51f5c73a66e4.png)

**Comment by eszlari** [comment]
I guess "Add clip or folder" doesn't invoke the portal dialog. CC @grulja

**Comment by eszlari** [comment]
https://bugs.kde.org/show_bug.cgi?id=406115

**Comment by glaubersm** [comment]
This bug persists. And the bug https://bugs.kde.org/show_bug.cgi?id=406115 affects folder selector, not the file open dialog shown in my screenshot. Could anyone reopen this bug report?
