### ISSUE TITLE
UI improperly sized on a HiDPI screen

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.kde.kdenlive#51]
I run an HiDPI screen and kdenlive UI doesn't look properly sized:

![image](https://user-images.githubusercontent.com/114441/80318427-0d0f1780-87d8-11ea-90b3-14178fd8085e.png)

If I force Qt5 to autoscale by adding `--env=QT_AUTO_SCREEN_SCALE_FACTOR=1`, I get this:

![image](https://user-images.githubusercontent.com/114441/80318440-287a2280-87d8-11ea-854a-20fc02f91e6b.png)

**Comment by eszlari** [comment]
https://invent.kde.org/kde/kdenlive/-/merge_requests/70

**Comment by hfiguiere** [comment]
That MR says:

> Under KDE Plasma the environment variable QT_SCREEN_SCALE_FACTORS is set, so it doesn't make a difference.

Which is just what my PR is doing: setting the environment (albeit I use `QT_AUTO_SCREEN_SCALE_FACTOR` because I don't assume one and let Qt detect). I saw no other evidence on not working right.

**Comment by eszlari** [comment]
From my understanding: the patch does the same, but was rejected by upstream. I would not like diverge from upstream.

**Comment by hfiguiere** [comment]
There is a difference. What upstream rejected is a patch in the code, that would also apply to other platform (I do believe they want to run on macOS and Windows). I wish the person closing would have been more explicit on the reasons, but I couldn't find evidence by searching that this is broken on 5.14 on Linux. Most of the other KDE app do it one way or the other.

This is just setting an env to run on Linux (I use GNOME so KDE Plasma doesn't apply here, even though I'm not even sure the env would be passed on).

**Comment by eszlari** [comment]
I did some more testing (Plasma and Windows, both 5.14) and there are indeed artifacts. Some fonts in

* Audio Spectrum
* Audio Mixer
* Vectorscope
* Waveform
* RGB Parade

are pixelated:

200%
![kdenlive_2x](https://user-images.githubusercontent.com/15569934/80447975-42704e00-891b-11ea-899f-60d1669f1df7.png)

100%
![kdenlive_1x](https://user-images.githubusercontent.com/15569934/80448333-3c2ea180-891c-11ea-9004-ffa34d8cc7d9.png)

Certainly not as bad as an unscaled app, but I'm not a video editor.

Also from https://doc.qt.io/qt-5/highdpi.html:
> The QT_ENABLE_HIGHDPI_SCALING environment variable, introduced in Qt 5.14, enables automatic scaling based on the pixel density of the monitor. Replaces QT_AUTO_SCREEN_SCALE_FACTOR.

**Comment by hfiguiere** [comment]
Arg they changed again. I'll try with that other one and update the PR since we control the runtime.

**Comment by eszlari** [comment]
I'm actually not sure, if there is really a difference between the two (maybe the new name is just more clear).
