### ISSUE TITLE
Kdenlive fails to apply selected color theme on start.

### ISSUE THREAD

**Issue by cyan-lime** [flathub/org.kde.kdenlive#53]
When starting the Kdenlive flatpak, the program displays a white interface like the one pictured, in spite of the color theme having been set to 'Breeze Dark'. Selecting the correct colour theme again causes the Breeze Dark look to display correctly, but upon closing and restarting the application, the problem surfaces again.

![image](https://user-images.githubusercontent.com/54386705/80577901-01775700-8a4b-11ea-8255-a063289ec0f2.png)

If it helps, I've also noticed that the colours the app takes on is not the built in Default / Breeze Light theme. The timeline at the bottom, for example, is slightly darker in the proper Breeze colours.

I'm running version 20.04.0 on Fedora Workstation 32.

**Comment by kerrongordon** [comment]
I am having the same problem version 20.04.0 on Fedora Workstation 32.

**Comment by eszlari** [comment]
filed an upstream bug:

https://invent.kde.org/multimedia/kdenlive/-/issues/693

**Comment by eszlari** [comment]
I tested this again with Fedora 34 / GNOME 40, and it seems to work.

Can anyone still reproduce this when run with:

```
flatpak run --env=XDG_CURRENT_DESKTOP=gnome org.kde.kdenlive
```
???
