### ISSUE TITLE
kdenlive.flatpak doesn't recognize the webcam

### ISSUE THREAD

**Issue by VosaXalo** [flathub/org.kde.kdenlive#54]
A couple of years ago I had already opened an issue about this problem. See here: [https://github.com/flathub/org.kde.kdenlive/issues/26](https://github.com/flathub/org.kde.kdenlive/issues/26)
It was resolved, but now it's here again.

I'm using the latest version 20.04.
My laptop, Dell XPS 13, has an integrated webcam, but Kdenlive doesn't recognize it. If I install Kdenlive from the repositories of Ubuntu 18.04 (DEB package), the webcam is recognized.
So, it's an issue of the flatpak package and not of Kdenlive.

**Comment by eszlari** [comment]
Seems to be an upstream problem, I opened issue there:
https://invent.kde.org/kde/kdenlive/-/issues/668
