### ISSUE TITLE
Export doesn't work

### ISSUE THREAD

**Issue by bertob** [flathub/org.kde.kdenlive#58]
![image](https://user-images.githubusercontent.com/1908896/82689009-1dd96e80-9c5a-11ea-887f-4546fa4b6036.png)

When trying to export a project from the main menu I get this error:

![image](https://user-images.githubusercontent.com/1908896/82689035-25007c80-9c5a-11ea-84d6-cc20306f19f1.png)

FWIW running the suggested pip command doesn't fix the problem, but of course this error dialog shouldn't happen in the first place :)

**Comment by bertob** [comment]
I feel like if this issue can't be fixed this package should be removed from Flathub until it is. Without the ability to export it's not very useful, and potentially gives people a bad impression of Flatpak/Flatpak.

**Comment by bertob** [comment]
I take that back, since apparently "export" isn't what you use to export the video, it's in "Project > Render". So the app works, it just has a weird menu structure.

**Comment by eszlari** [comment]
fixed: https://github.com/flathub/org.kde.kdenlive/commit/6de9955d4e183f0f5c49cc99782dc50e4fcb503e
