### ISSUE TITLE
Choosing location of output (rendered) file inserts another path

### ISSUE THREAD

**Issue by tstdin** [flathub/org.kde.kdenlive#6]
Description
-------------
After going to render section of projekt in kdenlive, there is a place for choosing output file. Right from it, there is a button (Select output destination), where you can browse your system directories and choose, where you want to have your output file. But when choosing e.g. "/home/user/Videos/test.mp4" it fills in "/run/user/1000/doc/d22257b0/test.mp4" instead.

Workaround
---------------
Write output file path of your own and don't use the button for browsing location.

**Comment by eszlari** [comment]
https://github.com/flatpak/flatpak/issues/1307
