### ISSUE TITLE
DVD Wizard  - Missing dependencies dvdauthor / mkisofs / genisoimage

### ISSUE THREAD

**Issue by alan-cole** [flathub/org.kde.kdenlive#61]
When opening the File > DVD Wizard, an error message shows:

`Program dvdauthor is required for the DVD wizard.Program mkisofs or genisoimage is required for the DVD wizard.`

![kdenlive-dvdwizard](https://user-images.githubusercontent.com/12739575/84555890-b8613500-ad62-11ea-9df6-4a7875736456.png)

**Comment by eszlari** [comment]
Are people still creating DVDs?

For this functionality, I think it would make more sense to add an app like DVDStyler (https://www.dvdstyler.org) to Flathub.

**Comment by tsdgeos** [comment]
People like integrated workflows, that's why kdenlive has that feature, so it would make sense to try to support it

**Comment by JamesBelchamber** [comment]
@alan-cole does this work?
```
flatpak install --user https://dl.flathub.org/build-repo/24550/org.kde.kdenlive.flatpakref
```

If it does (and "it works on my machine") then #70 can add the support.

**Comment by alan-cole** [comment]
Thanks @JamesBelchamber, I tried installing, however I get a 404 error.
```
$ flatpak install --user https://dl.flathub.org/build-repo/24550/org.kde.kdenlive.flatpakref
error: Can't load uri https://dl.flathub.org/build-repo/24550/org.kde.kdenlive.flatpakref: Server returned status 404: Not Found
```

**Comment by JamesBelchamber** [comment]
Probably timed out. Try this:

```
flatpak install --user https://dl.flathub.org/build-repo/25443/org.kde.kdenlive.flatpakref
```

**Comment by alan-cole** [comment]
@JamesBelchamber Just tested it out and all works as expected. Excellent work, thank you very much!

**Comment by JamesBelchamber** [comment]
Awesome. @tsdgeos could we get this merged?
