### ISSUE TITLE
Pitch compensation not working

### ISSUE THREAD

**Issue by aapjeisbaas** [flathub/org.kde.kdenlive#67]
It looks like the rubberband dependency is missing in the flathub version.
If this is installed you can change the speed of a clip while maintaining the original pitch.

**Comment by tsdgeos** [comment]
@eszlari will you have a look at this?

**Comment by tsdgeos** [comment]
@aapjeisbaas can you check if installing from
  flatpak install --user https://dl.flathub.org/build-repo/24331/org.kde.kdenlive.flatpakref
fixes the issue?

**Comment by aapjeisbaas** [comment]
@tsdgeos awesome thanks for the fix!

**Comment by yupthatguy** [comment]
I am having the same problem on Ubuntu 18.04 (ppa)... I added rubberband via `sudo apt install rubberband-cli` , but the problem was not solved..  any advice?

**Comment by eszlari** [comment]
> I am having the same problem on Ubuntu 18.04 (snap)... I added rubberband via `sudo apt install rubberband-cli` , but the problem was not solved.. any advice?

```
$ sudo apt install flatpak
$ flatpak remote-add flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak install org.kde.kdenlive

```
