### ISSUE TITLE
can not choose output directory

### ISSUE THREAD

**Issue by dirkjanl** [flathub/org.kde.kdenlive#7]
**Problems with directory of output file**
Sinds a while I have Kdenlive 17.12.2 on my laptop. Today I found out that I can not render a videofile to a directory in my homefolder (or else). When I have choosen the directory I wanted, it always comes back to:

/run/user/1000/doc/bc9960bb/namevideo.mp4

I have installed Kdenlive 17.12.2 by flatpack
Linux Mint 18.3, Cinnamon, 
21 februari 2018

**Comment by aleixpol** [comment]
@grulja what do you think?

**Comment by grulja** [comment]
That should be correct portal behaviour, that file is exported through document portal. With latest flatpak and xdg-desktop-portal it should return real path if the application has access to that directory which means document portal is not involved at all. Did you check whether that file exists in your homefolder after you rendered it?

**Comment by nedrichards** [comment]
Chances are that Linux mint doesn't have latest flatpak and
xdg-desktop-portals though, right?

**Comment by dirkjanl** [comment]
@grulja You asked me: "Did you check whether that file exists in your homefolder after you rendered it?". Which file you mean? The video file? 

At Settings I preset the Project directory: /home/dirkjanl/Stack/ProjectbestandKdenlive/

When I want to render The output directory that is shown is: /home/dirkjanl/.var/app/org.kde.kdenlive/cache/kdenlive//naamloos.mp4

And when I gave it a name The output directory is: /run/user/1000/doc/ba86a2a8/sabine3.mp4
while I selected: /home/dirkjanl/Stack/VideoKlaarDJ

After rendering the video is not in /home, not in /home/dirkjanl/ , not in /run/user/1000/doc/ba86a2a8/ and not in /home/dirkjanl/Stack/VideoKlaarDJ.

**Comment by dirkjanl** [comment]
I also see: yesterday I gave the project I was working with a name and stored in / home / dirkjanl / Stack / Project FileKdenlive. I do not see that name now, but I do have a folder with the name "1519222295710" which contains the three folders of the project: audiothumbs, preview and videothums. Only videothumbs contains some .png files from the project.

**Comment by dirkjanl** [comment]
I now see the file is hidden: In the project directory it has the name: .xdp_sabine3.EYAPEZ
In the saved video directory: .xdp_sabine3.5KOREZ. The video has been rendered in a correct way.

**Comment by nedrichards** [comment]
@dirkjanl can you run 
> flatpak --version
Looking at the [Linux mint packages page](http://packages.linuxmint.com/list.php?release=Sylvia) and searching for flatpak suggests that you have 0.10.0-0alexlarsson1~xenial and 0.8-0alexlarsson2~xenial of xdg-desktop-portal.

This bug is fixed in Flatpak 0.10.4 or newer and xdg-desktop-portal 0.10 or newer. You should ask Linux Mint to upgrade. Newer versions should be in the PPA so it shouldn't be too much trouble.

**Comment by dirkjanl** [comment]
Oké, I have uninstalled the Flatpak and wait till the xdg-desktop-portal is updated. Meanwhile I work with the AppImage.

**Comment by eszlari** [comment]
This was fixed in flatpak 0.11.4.

**Comment by joernalctl** [comment]
Hello guys. How are you doing?

I've the same problem as the one in the original post. 
The differences are in what concerns the system. I'm running Linux mint 19.3, and I had this problem using the snap version. The Flatpak seems to be working properly.
