### ISSUE TITLE
Upcoming 21.04 needs https support for ffmpeg

### ISSUE THREAD

**Issue by jlskuz** [flathub/org.kde.kdenlive#86]
For the upcoming 21.04 we need `--enable-gnutls` or `--enable-openssl` for ffmpeg (we need it for the rewritten online resource preview)

**Comment by eszlari** [comment]
Which would be preferable?

**Comment by jlskuz** [comment]
I don't really know. I tested with `--enable-gnutls` on the scriped for the nightly flatpak and it works fine. However in the appimage we use openssl for Qt as far as I know (not for ffmpeg yet), but this needs `--enable-nonfree`, which makes a bad impression to me (but I am not an expert for license concerns)
