### ISSUE TITLE
Unable to capture capture screen with audio

### ISSUE THREAD

**Issue by frdbr** [flathub/org.kde.kdenlive#87]
Unable to use the screen grab feature with audio:

Go to screen grab config and set the enconding profile to `x266 with audio`.

![image](https://user-images.githubusercontent.com/77309092/111890348-560b2400-89c7-11eb-8047-35388c35d2c4.png)

```
ffmpeg version 4.3.2 Copyright (c) 2000-2021 the FFmpeg developers built with gcc 10.2.0 (GCC) configuration: --prefix=/app --enable-rpath --enable-gpl --disable-static --enable-shared --disable-doc --disable-alsa --enable-libfontconfig --enable-libfreetype --enable-libopus --enable-libpulse --enable-librsvg --enable-libvpx --enable-libdav1d --enable-libxml2 --enable-libx264 --enable-libx265 --enable-libv4l2 --enable-libmp3lame --enable-vaapi --enable-libass --enable-nvenc
libavutil 56. 51.100 / 56. 51.100 libavcodec 58. 91.100 / 58. 91.100 libavformat 58. 45.100 / 58. 45.100 libavdevice 58. 10.100 / 58. 10.100
libavfilter 7. 85.100 / 7. 85.100 libswscale 5. 7.100 / 5. 7.100 libswresample 3. 7.100 / 3. 7.100 libpostproc 55. 7.100 / 55. 7.100
[x11grab @ 0x55ab1eccb440] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':0.0+0.0': Duration: N/A, start: 1616283924.657956, bitrate:
995328 kb/s
Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 995328 kb/s, 15 fps, 1000k tbr, 1000k tbn, 1000k tbc

Unknown input format: 'alsa'
```

**Comment by eszlari** [comment]
The ALSA device is not enabled in the FFmpeg compilation options. You can edit the profile in Kdenlive, changing `-f alsa` to `-f pulse`. I think, the default should be changed to `-f pulse` upstream.

**Comment by jlskuz** [comment]
Just changing to `-f pulse` doesn't work for me. I had to remove `-acodec libvorbis` too. We should at least have a additional profile (upstream) that works with the flatpak

**Comment by jlskuz** [comment]
See https://invent.kde.org/multimedia/kdenlive/-/commit/fe6d5e0b98ea688830d7fa5f78a07643a943125e

**Comment by eszlari** [comment]
Vorbis is an obsolete codec, but I guess that should be changed upstream.
