### ISSUE TITLE
Improve CJK support

### ISSUE THREAD

**Issue by frdbr** [flathub/org.kde.kdenlive#89]
Could you build the flatpak with fctix support to improve support for CJK languages?

Related: https://bugs.kde.org/show_bug.cgi?id=415420

**Comment by tsdgeos** [comment]
I'm going to guess this is more an issue of the runtime than kdenlive itself given that kdenlive doesn't have any mention for fxtix.

I'd suggest opening an issue https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues

**Comment by frdbr** [comment]
Ok, will do. Krita (and other apps) are also also affected by this: https://bugs.kde.org/show_bug.cgi?id=422465

**Comment by frdbr** [comment]
Should I close issue here?

**Comment by tsdgeos** [comment]
Yeah, let's close it. Once that one is fixed, if kdenlive still fails, then reopen it.
