### ISSUE TITLE
Rendering crash with WebM

### ISSUE THREAD

**Issue by tstdin** [flathub/org.kde.kdenlive#9]
Rendering of any file with WebM output causes crash (not of the entire application, just of the render process).
Other formats such as MP4 - H.264/H.265 works fine.

### Generic -> WebM
Error Log:
```
Rendering of /home/tom/Desktop/sample_rendered.webm crashed

(process:69): Gtk-WARNING **: Locale not supported by C library. Using the fallback 'C' locale.
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
[webm @ 0x7fb23c200c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead. [webm @ 0x7fb23c200c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
```
sample_rendered.webm.txt:
```
Started render process: /app/bin/melt /tmp/kdenlive_rendering_FAFcJ2.mlt in=0 out=388 -profile atsc_1080p_25 -consumer avformat:/home/tom/Desktop/sample_rendered.webm progress=1 f=webm vcodec=libvpx acodec=vorbis crf=23 vb=0 quality=good aq=6 max-intra-rate=1000 cpu-used=4 threads=1 real_time=-1
melt: Current Frame: 1, percentage: 0
melt: Current Frame: 3, percentage: 0
Rendering of /home/tom/Desktop/sample_rendered.webm aborted, resulting video will probably be corrupted.
```

### Ultra-High Definition -> WebM-VP9
Error Log:
```
Rendering of /home/tom/Desktop/sample_rendered.webm crashed

(process:149): Gtk-WARNING **: Locale not supported by C library. Using the fallback 'C' locale.
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
[webm @ 0x7f325c200c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead. [webm @ 0x7f325c200c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
```
sample_rendered.webm.txt:
```
Started render process: /app/bin/melt /tmp/kdenlive_rendering_DbFQC2.mlt in=0 out=388 -profile atsc_1080p_25 -consumer avformat:/home/tom/Desktop/sample_rendered.webm progress=1 f=webm acodec=vorbis vcodec=libvpx-vp9 crf=23 vb=0 quality=good aq=6 cpu-used=4 threads=1 real_time=-1
melt: Current Frame: 2, percentage: 0
melt: Current Frame: 5, percentage: 1
Rendering of /home/tom/Desktop/sample_rendered.webm aborted, resulting video will probably be corrupted.
```

**Comment by kafran** [comment]
Rendering of ./Batch1.webm crashed

(process:44): Gtk-WARNING **: Locale not supported by C library. Using the fallback 'C' locale.
Qt: Session management error: Could not open network socket
QApplication: invalid style override passed, ignoring it.
[swscaler @ 0x7f145c0008c0] Warning: data is not aligned! This can lead to a speed loss
[webm @ 0x7f1488200c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead. [webm @ 0x7f1488200c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.



Rendering of ./Batch1.webm crashed

(process:64): Gtk-WARNING **: Locale not supported by C library. Using the fallback 'C' locale.
Qt: Session management error: Could not open network socket
QApplication: invalid style override passed, ignoring it.
[swscaler @ 0x7f0e1c0008c0] Warning: data is not aligned! This can lead to a speed loss
[webm @ 0x7f0e48200c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead. [webm @ 0x7f0e48200c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.



Rendering of ./Batch1.webm crashed

(process:85): Gtk-WARNING **: Locale not supported by C library. Using the fallback 'C' locale.
Qt: Session management error: Could not open network socket
QApplication: invalid style override passed, ignoring it.
[swscaler @ 0x7f1aa80008c0] Warning: data is not aligned! This can lead to a speed loss
[webm @ 0x7f1ad4200c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead. [webm @ 0x7f1ad4200c80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.

**Comment by eszlari** [comment]
fixed: https://github.com/flathub/org.kde.kdenlive/commit/bb8a8c975affe3df060af99b9eafd9a5ff19789c
