### ISSUE TITLE
Vaapi not working

### ISSUE THREAD

**Issue by frdbr** [flathub/org.kde.kdenlive#92]
For VAAPI to work we must include: 

- [x] [libva](https://github.com/intel/libva)
- [x] [Intel(R) Media Driver for VAAPI](https://github.com/intel/media-driver)
- [x] [Intel(R) Graphics Memory Management Library](https://github.com/intel/gmmlib)
- [x] [Intel® Media SDK](https://github.com/Intel-Media-SDK/MediaSDK)
- [x] [Intel-vaapi-driver](https://github.com/intel/intel-vaapi-driver)

Also ffmpeg must be built with the following flags:

```
--extra-cflags="-I/usr/local/include" \
--extra-ldflags="-L/usr/local/lib" \
--enable-libmfx
--enable-vaapi

```

**Comment by Erick555** [comment]
See https://github.com/flathub/org.kde.kdenlive/pull/111#issuecomment-817288192

**Comment by frdbr** [comment]
> See [#111 (comment)](https://github.com/flathub/org.kde.kdenlive/pull/111#issuecomment-817288192)
> 
> > --extra-cflags="-I/usr/local/include" 
> > --extra-ldflags="-L/usr/local/lib" \
> 
> There is no `/usr/local` path in flatpak so this doesn't make any sense.

How can I point to the libs then? Where are they located at? 
> 
> > --enable-vaapi
> 
> it's already [there](https://github.com/flathub/org.kde.kdenlive/blob/master/org.kde.kdenlive.json#L486).

Yes, we only need libmfx now.

**Comment by Erick555** [comment]
> How can I point to the libs then? Where are they located at?

Libs are in `/app/lib` and `/usr/lib` but they should be detected automatically, why do you think you need setting them?

**Comment by frdbr** [comment]
> > How can I point to the libs then? Where are they located at?
> 
> Libs are in `/app/lib` and `/usr/lib` but they should be detected automatically, why do you think you need setting them?

This is how ffmpeg works it seems, one needs to explicitly pass this instructions to config for ffmpeg to work. It is also the case for nvidia:

```
--extra-cflags=-I/usr/local/cuda/include 
--extra-ldflags=-L/usr/local/cuda/lib64
```

**Comment by frdbr** [comment]
@Erick555 should I send a mr for intel-media-sdk or shall I open a request at freedesktop to include it?

**Comment by Erick555** [comment]
> This is how ffmpeg works it seems, one needs to explicitly pass this instructions at config stage. It is also the case for nvidia:

Do you have any example of something isn't working without this for this flatpak? There are couple of ffmpeg deps build here and there are no `extra-cflags` set so either ffmpeg is broken right now or you don't need to set those options.

**Comment by frdbr** [comment]
> > This is how ffmpeg works it seems, one needs to explicitly pass this instructions at config stage. It is also the case for nvidia:
> 
> Do you have any example of something isn't working without this currently? There are couple of ffmpeg deps build here and there are no `extra-cflags` set so either ffmpeg is broken right now or you don't need to set those options.
> 
> I didn't saw any other app that build ffmpeg setting such options.

I will add these changes to Kdenlive's flatpak nightly and ask some testing from the community to see if it works without the extra-cflags. But afaik this is the recommended way of doing in the ffmpeg docs and nvidia docs (as well as many posts on stackoverflow.)

**Comment by Erick555** [comment]
It may be recommended when something doesn't work. You didn't specified what doesn't work right now and you want to provide solution without stating what the problem is.

You don't need people to test this as it's enough to read the [buildlog](https://flathub.org/builds/api/v2/logs/1913553/raw) where you can see if ffmpeg can see external libraries or if it can't. You may also see that flatpak sets `LDFLAGS=-L/app/lib`, `LD_LIBRARY_PATH=/app/lib`,and `PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig` automatically so if you not inventing some fancy install prefixes for libraries they should be detected ootb. Only when they aren't you may try hacks from stackoverflow or elsewhere.

**Comment by frdbr** [comment]
The official documentation for both [intel](https://01.org/linuxmedia/quickstart/ffmpeg-vaapi-qsv-installation-environment) and [nvidia](https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/) recommend adding the extra flags. Will keep testing and if we encounter issues will open a new report. 

Closed via https://github.com/flathub/org.kde.kdenlive/pull/115

**Comment by Erick555** [comment]
Those aren't relevant for flatpak.
